package io.switchlite.adapter.common.module.render

import io.switchlite.adapter.common.api.EventBridge
import io.switchlite.adapter.common.module.Category
import io.switchlite.adapter.common.module.Module
import io.switchlite.adapter.common.option.float
import io.switchlite.adapter.common.render.RenderContext
import io.switchlite.adapter.common.ui.RenderUtils

/**
 * Keystrokes — in-game key/button press indicator (Raven-style).
 *
 * Draws a compact key grid showing the current state of the movement keys
 * (W/A/S/D), the jump key (SPACE), and the two mouse buttons (LMB/RMB). A key
 * lights up while it is held. It reads the live states that ForgeBootstrap /
 * FabricBootstrap already push into [EventBridge], so it also reflects the
 * synthetic clicks generated by AutoClicker (both read the same mouse state).
 *
 * Position and size are freely configurable:
 *  - Drag in-game by holding the left mouse button on the widget (moves posX/posY).
 *  - Scale is configurable from the WebUI.
 */
object Keystrokes : Module("Keystrokes", Category.RENDER) {

    // ── Position / size (free placement) ──

    @Volatile
    var posX: Int = 8
        private set
    @Volatile
    var posY: Int = 8
        private set

    /** Widget scale factor (1.0 = 100%). */
    var scale by float("Scale", 1.0f, 0.5f..2.0f)

    // ── Drag state ──

    private var dragging = false
    private var dragOffsetX = 0
    private var dragOffsetY = 0

    /**
     * Render the keystrokes widget. Called from OverlayRenderer on the MC render
     * thread (already in the main-thread Javassist hook). Handles drag + draw.
     */
    fun render(ctx: RenderContext) {
        if (!enabled) return
        handleDrag(ctx)
        draw(ctx)
    }

    // ═══════════════════════════════════════════
    //  Drag (free placement)
    // ═══════════════════════════════════════════

    private fun handleDrag(ctx: RenderContext) {
        val mx = EventBridge.guiMouseX
        val my = EventBridge.guiMouseY
        val leftDown = EventBridge.guiLeftMouseDown

        val size = cellSize(ctx)
        val w = size * 3 + 4 // 3 columns for WASD cluster
        val h = size * 3 + 4

        if (leftDown) {
            if (!dragging) {
                // Start dragging only if the press began inside the widget.
                if (mx in posX until posX + w && my in posY until posY + h) {
                    dragging = true
                    dragOffsetX = mx - posX
                    dragOffsetY = my - posY
                }
            } else {
                posX = mx - dragOffsetX
                posY = my - dragOffsetY
                clampToScreen(ctx)
            }
        } else {
            dragging = false
        }
    }

    private fun clampToScreen(ctx: RenderContext) {
        val size = cellSize(ctx)
        val w = size * 3 + 4
        val h = size * 3 + 4 + size // include jump row
        if (posX < 0) posX = 0
        if (posY < 0) posY = 0
        if (posX + w > ctx.scaledWidth) posX = ctx.scaledWidth - w
        if (posY + h > ctx.scaledHeight) posY = ctx.scaledHeight - h
    }

    // ═══════════════════════════════════════════
    //  Drawing (Raven-style key grid)
    // ═══════════════════════════════════════════

    private fun cellSize(ctx: RenderContext): Int = (22 * scale).toInt().coerceAtLeast(14)

    private fun draw(ctx: RenderContext) {
        val font = ctx.fontRenderer
        val size = cellSize(ctx)
        val x = posX
        val y = posY

        // ── WASD cluster (3x2 grid: W top-center; A/S/D bottom row) ──
        // W at (x+size+2, y); A/S/D at (x, y+size+2), (x+size+2, ...), (x+2size+4, ...)
        drawKey(ctx, "W", x + size + 2, y, size, EventBridge.isKeyForwardDown)
        drawKey(ctx, "A", x, y + size + 2, size, EventBridge.isKeyLeftDown)
        drawKey(ctx, "S", x + size + 2, y + size + 2, size, EventBridge.isKeyBackDown)
        drawKey(ctx, "D", x + 2 * size + 4, y + size + 2, size, EventBridge.isKeyRightDown)

        // ── Mouse buttons row (below WASD) ──
        val mouseY = y + 2 * size + 4
        drawKey(ctx, "LMB", x, mouseY, size, EventBridge.isLeftMousePhysicallyDown)
        drawKey(ctx, "RMB", x + size + 2, mouseY, size, EventBridge.isRightMousePhysicallyDown)

        // ── Jump key (SPACE), full width below mouse row ──
        val jumpY = mouseY + size + 2
        drawKey(ctx, "SPACE", x, jumpY, size * 2 + 2, EventBridge.isKeyJumpDown, wide = true)
    }

    /**
     * Draw one key cell. When [down] the cell is highlighted (lit up); otherwise it is dim.
     * Text is centered via the vanilla font's measured width. [wide] spans the full row.
     */
    private fun drawKey(ctx: RenderContext, label: String, x: Int, y: Int, size: Int, down: Boolean, wide: Boolean = false) {
        val font = ctx.fontRenderer
        val w = if (wide) size * 2 + 2 else size
        val h = size

        val bg = if (down) 0xC8FFFFFF.toInt() else 0x381A1A1A.toInt()
        val border = if (down) 0x80FFFFFF.toInt() else 0x24FFFFFF.toInt()

        RenderUtils.rect(ctx, x.toFloat(), y.toFloat(), w.toFloat(), h.toFloat(), bg)
        // Simple 1px border via an inset rect trick is not available; draw top/left edge lines.
        RenderUtils.rect(ctx, x.toFloat(), y.toFloat(), w.toFloat(), 1f, border)
        RenderUtils.rect(ctx, x.toFloat(), y.toFloat(), 1f, h.toFloat(), border)

        val textColor = if (down) 0xFF111111.toInt() else 0xCCFFFFFF.toInt()
        val textW = font.getStringWidth(label)
        val tx = x + (w - textW) / 2
        val ty = y + (h - font.fontHeight) / 2
        font.drawStringWithShadow(label, tx, ty, textColor)
    }
}
