// build.rs — build-time steps for the Rust injector:
//   1. Compile the C++ payload.dll (payload.cpp + attach_pipe.cpp) via the cc
//      crate — it discovers MSVC/GCC automatically (cmake was unreliable in
//      CI: silent exit 1 with no output). Needs jni.h for payload.cpp.
//   2. Generate a .rc that embeds agent.jar (RCDATA 101) + payload.dll
//      (RCDATA 102) into the exe, then embed it with embed-resource.
//
// resource.rs reads those IDs back out at runtime.

use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let resources_dir = manifest.join("resources");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // ── 1. Compile payload.dll (C++) via the cc crate ──
    // Needs jni.h: find it via JAVA_HOME, or the JDK on PATH (CI sets up JDK 8).
    let jni_include = find_jni_include();

    let mut payload_built = None;
    if !jni_include.is_empty() {
        let mut build = cc::Build::new();
        build
            .cargo_metadata(false) // we link manually, not into the Rust crate
            .cpp(true)
            .shared_flag(true)
            .flag_if_supported("/EHsc")
            .include(&jni_include)
            .file(manifest.join("src/payload/payload.cpp"))
            .file(manifest.join("src/payload/attach_pipe.cpp"));

        // Link psapi (payload uses psapi functions)
        if env::consts::OS == "windows" {
            build.flag_if_supported("/DPSAPI_VERSION=2");
        }

        let compile_result = build.try_compile("switchlite_payload");
        match compile_result {
            Ok(()) => {
                // cc::Build writes the artifact into OUT_DIR; find it.
                let candidate = out_dir.join("libswitchlite_payload.dll");
                let candidate2 = out_dir.join("switchlite_payload.dll");
                if candidate.exists() {
                    payload_built = Some(candidate);
                } else if candidate2.exists() {
                    payload_built = Some(candidate2);
                } else {
                    println!(
                        "cargo:warning=payload compiled but dll not found in {} (expected libswitchlite_payload.dll)",
                        out_dir.display()
                    );
                }
            }
            Err(e) => {
                println!("cargo:warning=cc compile payload FAILED: {}", e);
            }
        }
    } else {
        println!("cargo:warning=jni.h not found (JAVA_HOME missing) — payload.dll not built");
    }

    finish_embed(&manifest, &resources_dir, &out_dir, payload_built.as_ref());
}

/// Locate the JNI include dir (containing jni.h).
fn find_jni_include() -> String {
    // 1. JAVA_HOME
    if let Ok(jh) = env::var("JAVA_HOME") {
        let p = PathBuf::from(&jh).join("include");
        if p.join("jni.h").exists() {
            return p.to_string_lossy().into_owned();
        }
    }
    // 2. java on PATH → resolve include dir
    if let Ok(out) = Command::new("java")
        .arg("-XshowSettings:properties")
        .arg("-version")
        .output()
    {
        let text = String::from_utf8_lossy(&out.stderr);
        if let Some(line) = text.lines().find(|l| l.contains("java.home")) {
            if let Some(val) = line.split('=').nth(1) {
                let p = PathBuf::from(val.trim()).join("include");
                if p.join("jni.h").exists() {
                    return p.to_string_lossy().into_owned();
                }
            }
        }
    }
    String::new()
}

/// Generate resources.rc and embed via embed-resource.
fn finish_embed(
    manifest: &PathBuf,
    resources_dir: &PathBuf,
    out_dir: &PathBuf,
    payload_dll: Option<&PathBuf>,
) {
    // Locate agent.jar (CI copies it into resources/ before cargo build)
    let agent_jar = resources_dir.join("agent.jar");

    // Pick the payload.dll source: freshly built, else resources/payload.dll
    let payload_source = match payload_dll {
        Some(p) => p.clone(),
        None => resources_dir.join("payload.dll"),
    };

    let mut rc = String::new();
    rc.push_str("// Auto-generated by build.rs — embed agent.jar + payload.dll as RCDATA\n");
    rc.push_str("#include <windows.h>\n");
    rc.push_str("#define AGENT_JAR_RCDATA 101\n");
    rc.push_str("#define PAYLOAD_DLL_RCDATA 102\n");

    let agent_rc_path = out_dir.join("agent.jar");
    if agent_jar.exists() {
        let _ = std::fs::copy(&agent_jar, &agent_rc_path);
        rc.push_str(&format!(
            "AGENT_JAR_RCDATA RCDATA \"{}\"\n",
            agent_rc_path.to_string_lossy().replace('\\', "\\\\")
        ));
        println!("cargo:rerun-if-changed={}", agent_jar.display());
    } else {
        println!("cargo:warning=resources/agent.jar not found — exe will lack embedded agent.jar");
    }

    let dll_rc_path = out_dir.join("payload.dll");
    if payload_source.exists() {
        let _ = std::fs::copy(&payload_source, &dll_rc_path);
        rc.push_str(&format!(
            "PAYLOAD_DLL_RCDATA RCDATA \"{}\"\n",
            dll_rc_path.to_string_lossy().replace('\\', "\\\\")
        ));
        println!("cargo:rerun-if-changed={}", payload_source.display());
    } else {
        println!("cargo:warning=payload.dll not found — exe will lack embedded payload.dll");
    }

    let rc_path = out_dir.join("resources.rc");
    let _ = std::fs::write(&rc_path, rc);

    // embed-resource's compile() returns () — it compiles + links the .rc.
    embed_resource::compile(rc_path.to_str().unwrap(), embed_resource::NONE);
    println!("cargo:warning=embedded agent.jar + payload.dll resources");
}
