// build.rs — build-time steps for the Rust injector:
//   Embed agent.jar (RCDATA 101) + payload.dll (RCDATA 102) into the exe via
//   embed-resource. Both artifacts are prepared by CI BEFORE cargo build:
//     - agent.jar   -> resources/agent.jar   (copied from the JVM job)
//     - payload.dll -> resources/payload.dll (built by cmake in CI, then
//                                             copied here by the CI step)
//   resource.rs reads those IDs back out at runtime.
//
// We deliberately do NOT compile C++ inside build.rs: the MSVC environment
// (vcvars INCLUDE/LIB) is not reliably available to a bare cargo build script,
// which caused repeated cl.exe failures. C++ is built by CI's own cmake step.

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let resources_dir = manifest.join("resources");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut rc = String::new();
    rc.push_str("// Auto-generated by build.rs — embed agent.jar + payload.dll as RCDATA\n");
    rc.push_str("#include <windows.h>\n");
    rc.push_str("#define AGENT_JAR_RCDATA 101\n");
    rc.push_str("#define PAYLOAD_DLL_RCDATA 102\n");

    let agent_jar = resources_dir.join("agent.jar");
    let agent_rc_path = out_dir.join("agent.jar");
    if agent_jar.exists() {
        let _ = std::fs::copy(&agent_jar, &agent_rc_path);
        rc.push_str(&format!(
            "AGENT_JAR_RCDATA RCDATA \"{}\"\n",
            agent_rc_path.to_string_lossy().replace('\\', "\\\\")
        ));
        println!("cargo:rerun-if-changed={}", agent_jar.display());
    } else {
        println!("cargo:warning=resources/agent.jar not found — exe will lack embedded agent.jar");
    }

    let payload_dll = resources_dir.join("payload.dll");
    let dll_rc_path = out_dir.join("payload.dll");
    if payload_dll.exists() {
        let _ = std::fs::copy(&payload_dll, &dll_rc_path);
        rc.push_str(&format!(
            "PAYLOAD_DLL_RCDATA RCDATA \"{}\"\n",
            dll_rc_path.to_string_lossy().replace('\\', "\\\\")
        ));
        println!("cargo:rerun-if-changed={}", payload_dll.display());
    } else {
        println!("cargo:warning=resources/payload.dll not found — exe will lack embedded payload.dll");
    }

    let rc_path = out_dir.join("resources.rc");
    let _ = std::fs::write(&rc_path, rc);

    // embed-resource's compile() returns () — it compiles + links the .rc.
    embed_resource::compile(rc_path.to_str().unwrap(), embed_resource::NONE);
    println!("cargo:warning=embedded agent.jar + payload.dll resources");
}
