// build.rs — build-time steps for the Rust injector:
//   1. Build the C++ payload.dll (cmake + JDK jni.h) — the in-process JNI
//      attach DLL that Rust injects via CreateRemoteThread.
//   2. Generate a .rc that embeds agent.jar (RCDATA 101) + payload.dll
//      (RCDATA 102) into the exe, then embed it with embed-resource.
//
// resource.rs reads those IDs back out at runtime.

use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let resources_dir = manifest.join("resources");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // ── 1. Build payload.dll (C++) via cmake ──
    // Needs jni.h: find it via JAVA_HOME, or the JDK on PATH (CI sets up JDK 8).
    let jni_include = find_jni_include();

    let payload_build_dir = out_dir.join("payload-build");
    let _ = std::fs::create_dir_all(&payload_build_dir);

    let cmake = env::var("CMAKE").unwrap_or_else(|_| "cmake".to_string());
    let cmake_configure = Command::new(&cmake)
        .arg("-S")
        .arg(manifest.join("src/payload"))
        .arg("-B")
        .arg(&payload_build_dir)
        .arg(format!("-DJNI_INCLUDE_DIR={}", jni_include))
        .arg("-DCMAKE_BUILD_TYPE=Release")
        .status();
    match cmake_configure {
        Ok(status) if status.success() => {}
        other => {
            println!(
                "cargo:warning=cmake configure payload: {:?} (payload.dll build skipped; sidecar path fallback in resource.rs)",
                other.map(|s| s.code())
            );
            // Continue — resource.rs falls back to a sidecar payload.dll.
            return finish_embed(&manifest, &resources_dir, &out_dir, None);
        }
    }

    let cmake_build = Command::new(&cmake)
        .arg("--build")
        .arg(&payload_build_dir)
        .arg("--config")
        .arg("Release")
        .status();
    match cmake_build {
        Ok(status) if status.success() => {}
        other => {
            println!(
                "cargo:warning=cmake build payload: {:?} (payload.dll build skipped)",
                other.map(|s| s.code())
            );
            return finish_embed(&manifest, &resources_dir, &out_dir, None);
        }
    }

    // Locate built payload.dll
    let payload_dll = payload_build_dir
        .join("Release")
        .join("payload.dll");
    let payload_dll = if payload_dll.exists() {
        payload_dll
    } else {
        payload_build_dir.join("payload.dll")
    };

    finish_embed(&manifest, &resources_dir, &out_dir, Some(&payload_dll));
}

/// Locate the JNI include dir (containing jni.h).
fn find_jni_include() -> String {
    // 1. JAVA_HOME
    if let Ok(jh) = env::var("JAVA_HOME") {
        let p = PathBuf::from(&jh).join("include");
        if p.join("jni.h").exists() {
            return p.to_string_lossy().into_owned();
        }
    }
    // 2. java on PATH → resolve include dir
    if let Ok(out) = Command::new("java").arg("-XshowSettings:properties").arg("-version").output() {
        let text = String::from_utf8_lossy(&out.stderr);
        if let Some(line) = text.lines().find(|l| l.contains("java.home")) {
            if let Some(val) = line.split('=').nth(1) {
                let p = PathBuf::from(val.trim()).join("include");
                if p.join("jni.h").exists() {
                    return p.to_string_lossy().into_owned();
                }
            }
        }
    }
    String::new()
}

/// Generate resources.rc and embed via embed-resource.
fn finish_embed(
    manifest: &PathBuf,
    resources_dir: &PathBuf,
    out_dir: &PathBuf,
    payload_dll: Option<&PathBuf>,
) {
    // Locate agent.jar (CI copies it into resources/ before cargo build)
    let agent_jar = resources_dir.join("agent.jar");

    // Pick the payload.dll source: freshly built, else resources/payload.dll
    let payload_source = match payload_dll {
        Some(p) => p.clone(),
        None => resources_dir.join("payload.dll"),
    };

    let mut rc = String::new();
    rc.push_str("// Auto-generated by build.rs — embed agent.jar + payload.dll as RCDATA\n");
    rc.push_str("#include <windows.h>\n");
    rc.push_str("#define AGENT_JAR_RCDATA 101\n");
    rc.push_str("#define PAYLOAD_DLL_RCDATA 102\n");

    let agent_rc_path = out_dir.join("agent.jar");
    if agent_jar.exists() {
        let _ = std::fs::copy(&agent_jar, &agent_rc_path);
        rc.push_str(&format!(
            "AGENT_JAR_RCDATA RCDATA \"{}\"\n",
            agent_rc_path.to_string_lossy().replace('\\', "\\\\")
        ));
        println!("cargo:rerun-if-changed={}", agent_jar.display());
    } else {
        println!("cargo:warning=resources/agent.jar not found — exe will lack embedded agent.jar");
    }

    let dll_rc_path = out_dir.join("payload.dll");
    if payload_source.exists() {
        let _ = std::fs::copy(&payload_source, &dll_rc_path);
        rc.push_str(&format!(
            "PAYLOAD_DLL_RCDATA RCDATA \"{}\"\n",
            dll_rc_path.to_string_lossy().replace('\\', "\\\\")
        ));
        println!("cargo:rerun-if-changed={}", payload_source.display());
    } else {
        println!("cargo:warning=payload.dll not found — exe will lack embedded payload.dll");
    }

    let rc_path = out_dir.join("resources.rc");
    let _ = std::fs::write(&rc_path, rc);

    match embed_resource::compile(rc_path.to_str().unwrap(), embed_resource::NONE) {
        Ok(_) => println!("cargo:warning=embedded agent.jar + payload.dll resources"),
        Err(e) => println!("cargo:warning=embed-resource failed: {}", e),
    }
}
